steps:
- name: gcr.io/cloud-builders/docker
  args: 
    - build
    - --tag=gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}
    - --tag=gcr.io/$PROJECT_ID/helm:latest
    - --build-arg
    - HELM_VERSION=v${_HELM_VERSION}
    - .

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - $_IMAGE_LOCATION
    - -a

# Sanity Check: make sure basic functionality works
- name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['version', '--client']
  env:
    - SKIP_CLUSTER_CONFIG=true

tags: ['cloud-builders-community']

substitutions:
  _HELM_VERSION: 3.15.4
  _IMAGE_LOCATION: us-docker.pkg.dev/optoro-artifacts/cloud-run-helm-charts