steps:
- name: gcr.io/cloud-builders/docker
  dir: helm
  args:
    - build
    - --tag=$_IMAGE_LOCATION:$_HELM_VERSION
    - --tag=gcr.io/$PROJECT_ID/helm:latest
    - --build-arg
    - HELM_VERSION=v${_HELM_VERSION}
    - .

- name: gcr.io/cloud-builders/docker
  dir: helm
  args:
    - push
    - $_IMAGE_LOCATION
    - -a

tags: ['cloud-builders-community']

substitutions:
  _HELM_VERSION: 3.15.4
  _IMAGE_LOCATION: us-docker.pkg.dev/optoro-artifacts/cloud-run-helm-charts/helm